name: autogenerate-json

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: node script/generate_json.js
      # Don't auto-commit back into GitHub, just let Vercel use the JSON in its build